#!/bin/sh
for f in data/parser/*-test; do
 c=`echo $f | sed -e 's:.*/::g'`;
 num=`echo $c | sed -e 's:[^0-9]::g'`

 echo "http://localhost:8888/cookie-parser?$num"
done

python ../tools/testserver/testserver.py --data-dir data
